name: torn_pda
description: Torn City personal assistant

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
#version: 1.0.0

environment:
  sdk: ">=3.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  android_intent_plus: 5.0.2
  animations: 2.0.2
  app_badge_plus: 1.0.0
  app_links: 4.0.1
  app_settings: 5.1.1
  audioplayers: 6.0.0
  bot_toast: 4.1.3
  cloud_firestore: 4.16.1
  cloud_functions: 4.7.1
  connectivity_plus: 5.0.2
  cookie_jar: 3.0.1
  crypto: 3.0.3
  cupertino_icons: 1.0.2
  dart_ping: 8.0.1
  dart_ping_ios: 3.0.0
  dbcrypt: 2.0.0
  dio: 5.0.3
  device_info_plus: 9.1.2
  dotted_border: 2.0.0+2
  easy_rich_text: 2.0.0
  expandable: 5.0.1
  ## ffi ^ to avoid strut errors
  ## ffi: ^1.0.0
  firebase_analytics: 10.10.1
  firebase_auth: 4.19.1
  firebase_core: 2.29.0
  firebase_crashlytics: 3.5.1
  firebase_database: 10.5.1
  firebase_messaging: 14.8.1
  firebase_remote_config: 4.4.1
  fl_chart: 0.68.0
  flex_color_picker: 3.5.0
  flutter_font_icons: 2.2.5
  flutter_inappwebview: 6.0.0
  #flutter_inappwebview:
  #  git:
  #    url: https://github.com/Manuito83/flutter_inappwebview.git
  #    ref: manuito-beta22
  flutter_local_notifications: 17.0.1
  flutter_native_splash: 2.4.0
  flutter_secure_storage: 9.2.1
  flutter_slidable: 3.0.1
  flutter_speed_dial: 7.0.0
  flutter_xlider: 3.5.0
  workmanager: 0.5.2
  font_awesome_flutter: 10.4.0
  # Temporary as per https://github.com/jonataslaw/getx/issues/3100
  get:
    git:
      url: https://github.com/Aniketkhote/getx.git
      ref: master
  home_widget:
    git:
      url: https://github.com/Manuito83/home_widget.git
      ref: pda-dev  ## TODO: merge into pda-stable
  html: 0.15.4
  http: 0.13.6
  lints: 2.1.1
  ## flutter pub run import_sorter:main
  import_sorter: 4.6.0
  intl: 0.17.0
  material_design_icons_flutter: 5.0.5955-rc.1 ## Breaking changes in minor versions
  path_provider: 2.1.3
  percent_indicator: 4.2.2
  provider: 6.1.2
  pull_to_refresh: 2.0.0
  quick_actions: 1.0.5
  receive_intent: 0.2.5
  rxdart: 0.27.7
  share_plus: 9.0.0
  shared_preferences: 2.0.15
  showcaseview: 
    git: 
      url: https://github.com/chandrabezzo/flutter_showcaseview
      ref: bugfix/text-theme/removed-3.22
  sliding_up_panel: 2.0.0+1
  timeline_tile: 2.0.0
  timezone: 0.9.1
  toggle_switch: 2.3.0
  url_launcher: 6.2.1
  vibration: 1.8.4
  wakelock_plus: 1.2.4
  webview_flutter: 4.7.0
  collection: 1.18.0

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/icons/torn_pda.png"
  image_path_ios: "images/icons/torn_pda_ios.jpg"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/awards/
    - images/awards/honors/
    - images/awards/medals/
    - images/awards/categories/
    - images/flags/stock/
    - images/flags/travel/
    - images/flags/ball/
    - images/icons/
    - images/icons/cooldowns/
    - images/icons/map/
    - images/icons/inventory/
    - images/icons/home/
    - images/icons/status/
    - images/icons/rarity/
    - images/torn_items/small/
    - images/npcs/
    - sounds/alerts/
    - userscripts/TornPDA_Ready.js
    - userscripts/TornPDA_API.js
    - userscripts/TornPDA_EvaluateJavascript.js

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Visitor
      fonts:
        - asset: fonts/visitor.ttf
  